### ISSUE TITLE
submitting proof FAILED a proof submission for some reason : could not access network: fatal network error: not enough money for denomination MEL

### ISSUE THREAD

**Issue by lakshmanpython** [mel-project/melminter#18]

**Comment by lakshmanpython** [comment]
Hi Team

i can see the exception as below

submitting proof FAILED a proof submission for some reason : could not access network: fatal network error: not enough money for denomination MEL
 submitting proof FAILED a proof submission for some reason : could not access network: fatal network error: not enough money for denomination MEL
 submitting proof FAILED a proof submission for some reason : could not access network: fatal network error: not enough money for denomination MEL
 submitting proof minted 1.176578 ERG                                           
 submitting proof minted 1.176578 ERG                                           
 submitting proof minted 1.176578 ERG                                           
 submitting proof minted 1.176578 ERG                                           
 submitting proof minted 1.176578 ERG                                           
 submitting proof minted 1.176059 ERG                                           
 submitting proof minted 1.176059 ERG                                           
           worker CONVERTING 18.033965 ERG!                                     
           worker transferring 6.582416 MEL of profits to backup wallet         
           worker Selected difficulty: 32 (approx. 54215.4981376s / tx)
           worker Max speed on chain: 8947.85 kH/s

**Comment by ArtoriaShirou** [comment]
Same issue as #16, corresponding issue has been reopened.

**Comment by lakshmanpython** [comment]
Thanks
